name: Instrument

on:
  workflow_dispatch:

jobs:
  instrument:
    uses: iAppSecure-Solution-Pvt-Ltd/JAVA-IAST/.github/workflows/Instrument.yml@main  # Reference the reusable workflow
    with:
      working_directory: Remote  # Set the working directory
      FusionLiteProject: ${{ github.event.repository.name }}  # Pass the repository name as FusionLiteProject
      ApplicationFile: 'AltoroJ.war'  # Application file passed by the user
      InstrumentedFile: 'AltoroJ.war'  # Use the same file for InstrumentedFile
