name: Instrument

on:
  workflow_dispatch:
    inputs:
      application_file:
        description: 'The application file to use for the Instrument'
        required: true
        default: 'AltoroJ.war'

jobs:
  trigger-build:
    uses: iAppSecure-Solution-Pvt-Ltd/JAVA-IAST/.github/workflows/Instrument.yml@main  # Reference the reusable workflow
    with:
      working_directory: ${{ github.workspace }}/Remote  # Set the working directory
      FusionLiteProject: ${{ github.event.repository.name }}  # Pass the repository name as FusionLiteProject
      ApplicationFile: ${{ github.event.inputs.application_file }}  # Application file passed by the user
      InstrumentedFile: ${{ github.event.inputs.application_file }}  # Use the same file for InstrumentedFile
